# Item-Based Collaborative Filtering

Importing the MovieLens 100K data set into a pandas DataFrame:

In [1]:
import pandas as pd

r_cols = ['user_id', 'movie_id', 'rating']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols, usecols=range(3), encoding="ISO-8859-1")

m_cols = ['movie_id', 'title']
movies = pd.read_csv('ml-100k/u.item', sep='|', names=m_cols, usecols=range(2), encoding="ISO-8859-1")

ratings = pd.merge(movies, ratings)

ratings.head()

movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

We'll pivot this table to construct a nice matrix of users and the movies they rated. NaN indicates missing data, or movies that a given user did not watch:

In [2]:
userRatings = ratings.pivot_table(index=['user_id'],columns=['title'],values='rating')
userRatings.head()

title    'Til There Was You (1997)  1-900 (1994)  101 Dalmatians (1996)  \
user_id                                                                   
0                              NaN           NaN                    NaN   
1                              NaN           NaN                    2.0   
2                              NaN           NaN                    NaN   
3                              NaN           NaN                    NaN   
4                              NaN           NaN                    NaN   

title    12 Angry Men (1957)  187 (1997)  2 Days in the Valley (1996)  \
user_id                                                                 
0                        NaN         NaN                          NaN   
1                        5.0         NaN                          NaN   
2                        NaN         NaN                          NaN   
3                        NaN         2.0                          NaN   
4                        NaN         NaN                          NaN   

title    20,000 Leagues Under the Sea (1954)  2001: A Space Odyssey (1968)  \
user_id                                                                      
0                                        NaN                           NaN   
1                                        3.0                           4.0   
2                                        NaN                           NaN   
3                                        NaN                           NaN   
4                                        NaN                           NaN   

title    3 Ninjas: High Noon At Mega Mountain (1998)  39 Steps, The (1935)  \
user_id                                                                      
0                                                NaN                   NaN   
1                                                NaN                   NaN   
2                                                1.0                   NaN   
3                                                NaN                   NaN   
4                                                NaN                   NaN   

title                   ...                  Yankee Zulu (1994)  \
user_id                 ...                                       
0                       ...                                 NaN   
1                       ...                                 NaN   
2                       ...                                 NaN   
3                       ...                                 NaN   
4                       ...                                 NaN   

title    Year of the Horse (1997)  You So Crazy (1994)  \
user_id                                                  
0                             NaN                  NaN   
1                             NaN                  NaN   
2                             NaN                  NaN   
3                             NaN                  NaN   
4                             NaN                  NaN   

title    Young Frankenstein (1974)  Young Guns (1988)  Young Guns II (1990)  \
user_id                                                                       
0                              NaN                NaN                   NaN   
1                              5.0                3.0                   NaN   
2                              NaN                NaN                   NaN   
3                              NaN                NaN                   NaN   
4                              NaN                NaN                   NaN   

title    Young Poisoner's Handbook, The (1995)  Zeus and Roxanne (1997)  \
user_id                                                                   
0                                          NaN                      NaN   
1                                          NaN                      NaN   
2                                          NaN                      NaN   
3                                          NaN                

Pandas has a built-in corr() method that will compute a correlation score for every column pair in the matrix! This gives us a correlation score between every pair of movies (where at least one user rated both movies - otherwise NaN's will show up.

In [3]:
corrMatrix = userRatings.corr()
corrMatrix.head()

title                      'Til There Was You (1997)  1-900 (1994)  \
title                                                                
'Til There Was You (1997)                        1.0           NaN   
1-900 (1994)                                     NaN           1.0   
101 Dalmatians (1996)                           -1.0           NaN   
12 Angry Men (1957)                             -0.5           NaN   
187 (1997)                                      -0.5           NaN   

title                      101 Dalmatians (1996)  12 Angry Men (1957)  \
title                                                                   
'Til There Was You (1997)              -1.000000            -0.500000   
1-900 (1994)                                 NaN                  NaN   
101 Dalmatians (1996)                   1.000000            -0.049890   
12 Angry Men (1957)                    -0.049890             1.000000   
187 (1997)                              0.269191             0.666667   

title                      187 (1997)  2 Days in the Valley (1996)  \
title                                                                
'Til There Was You (1997)   -0.500000                     0.522233   
1-900 (1994)                      NaN                          NaN   
101 Dalmatians (1996)        0.269191                     0.048973   
12 Angry Men (1957)          0.666667                     0.256625   
187 (1997)                   1.000000                     0.596644   

title                      20,000 Leagues Under the Sea (1954)  \
title                                                            
'Til There Was You (1997)                                  NaN   
1-900 (1994)                                               NaN   
101 Dalmatians (1996)                                 0.266928   
12 Angry Men (1957)                                   0.274772   
187 (1997)                                                 NaN   

title                      2001: A Space Odyssey (1968)  \
title                                                     
'Til There Was You (1997)                     -0.426401   
1-900 (1994)                                  -0.981981   
101 Dalmatians (1996)                         -0.043407   
12 Angry Men (1957)                            0.178848   
187 (1997)                                    -0.554700   

title                      3 Ninjas: High Noon At Mega Mountain (1998)  \
title                                                                    
'Til There Was You (1997)                                          NaN   
1-900 (1994)                                                       NaN   
101 Dalmatians (1996)                                              NaN   
12 Angry Men (1957)                                                NaN   
187 (1997)                                                         NaN   

title                      39 Steps, The (1935)  \
title                                             
'Til There Was You (1997)                   NaN   
1-900 (1994)                                NaN   
101 Dalmatians (1996)                  0.111111   
12 Angry Men (1957)                    0.457176   
187 (1997)                             1.000000   

title                                     ...                  \
title                                     ...                   
'Til There Was You (1997)                 ...                   
1-900 (1994)                              ...                   
101 Dalmatians (1996)                     ...                   
12 Angry Men (1957)                       ...                   
187 (1997)                                ...                   

title                      Yankee Zulu (1994)  Year of the Horse (1997)  \
title                                                                     
'Til There Was You (1997)                 NaN                       NaN   
1-900 (1994)                              NaN                       NaN

A handful of users that happened to rate the same pair of movies. In order to restrict our results to movies that lots of people rated together - and also give us more popular results that are more easily recongnizable - we'll use the min_periods argument to throw out results where fewer than 100 users rated a given movie pair:

In [4]:
corrMatrix = userRatings.corr(method='pearson', min_periods=100)
corrMatrix.head()

title                      'Til There Was You (1997)  1-900 (1994)  \
title                                                                
'Til There Was You (1997)                        NaN           NaN   
1-900 (1994)                                     NaN           NaN   
101 Dalmatians (1996)                            NaN           NaN   
12 Angry Men (1957)                              NaN           NaN   
187 (1997)                                       NaN           NaN   

title                      101 Dalmatians (1996)  12 Angry Men (1957)  \
title                                                                   
'Til There Was You (1997)                    NaN                  NaN   
1-900 (1994)                                 NaN                  NaN   
101 Dalmatians (1996)                        1.0                  NaN   
12 Angry Men (1957)                          NaN                  1.0   
187 (1997)                                   NaN                  NaN   

title                      187 (1997)  2 Days in the Valley (1996)  \
title                                                                
'Til There Was You (1997)         NaN                          NaN   
1-900 (1994)                      NaN                          NaN   
101 Dalmatians (1996)             NaN                          NaN   
12 Angry Men (1957)               NaN                          NaN   
187 (1997)                        NaN                          NaN   

title                      20,000 Leagues Under the Sea (1954)  \
title                                                            
'Til There Was You (1997)                                  NaN   
1-900 (1994)                                               NaN   
101 Dalmatians (1996)                                      NaN   
12 Angry Men (1957)                                        NaN   
187 (1997)                                                 NaN   

title                      2001: A Space Odyssey (1968)  \
title                                                     
'Til There Was You (1997)                           NaN   
1-900 (1994)                                        NaN   
101 Dalmatians (1996)                               NaN   
12 Angry Men (1957)                                 NaN   
187 (1997)                                          NaN   

title                      3 Ninjas: High Noon At Mega Mountain (1998)  \
title                                                                    
'Til There Was You (1997)                                          NaN   
1-900 (1994)                                                       NaN   
101 Dalmatians (1996)                                              NaN   
12 Angry Men (1957)                                                NaN   
187 (1997)                                                         NaN   

title                      39 Steps, The (1935)  \
title                                             
'Til There Was You (1997)                   NaN   
1-900 (1994)                                NaN   
101 Dalmatians (1996)                       NaN   
12 Angry Men (1957)                         NaN   
187 (1997)                                  NaN   

title                                     ...                  \
title                                     ...                   
'Til There Was You (1997)                 ...                   
1-900 (1994)                              ...                   
101 Dalmatians (1996)                     ...                   
12 Angry Men (1957)                       ...                   
187 (1997)                                ...                   

title                      Yankee Zulu (1994)  Year of the Horse (1997)  \
title                                                                     
'Til There Was You (1997)                 NaN                       NaN   
1-900 (1994)                              NaN                       NaN

I'll extract the ratings from the userRatings DataFrame, and use dropna() to get rid of missing data (leaving me only with a Series of the movies I actually rated)

In [5]:
myRatings = userRatings.loc[0].dropna()
myRatings

title
Empire Strikes Back, The (1980)    5.0
Gone with the Wind (1939)          1.0
Star Wars (1977)                   5.0
Name: 0, dtype: float64

Now, let's go through each movie I rated one at a time, and build up a list of possible recommendations based on the movies similar to the ones I rated.

So for each movie I rated, I'll retrieve the list of similar movies from our correlation matrix. I'll then scale those correlation scores by how well I rated the movie they are similar to, so movies similar to ones I liked count more than movies similar to ones I hated:

In [6]:
simCandidates = pd.Series()
for i in range(0, len(myRatings.index)):
    print ("Adding sims for " + myRatings.index[i] + "...")
    # Retrieve similar movies to this one that I rated
    sims = corrMatrix[myRatings.index[i]].dropna()
    # Now scale its similarity by how well I rated this movie
    sims = sims.map(lambda x: x * myRatings[i])
    # Add the score to the list of similarity candidates
    simCandidates = simCandidates.append(sims)
    
#Glance at our results so far:
print ("sorting...")
simCandidates.sort_values(inplace = True, ascending = False)
print (simCandidates.head(10))

Adding sims for Empire Strikes Back, The (1980)...
Adding sims for Gone with the Wind (1939)...
Adding sims for Star Wars (1977)...
sorting...
Empire Strikes Back, The (1980)                       5.000000
Star Wars (1977)                                      5.000000
Empire Strikes Back, The (1980)                       3.741763
Star Wars (1977)                                      3.741763
Return of the Jedi (1983)                             3.606146
Return of the Jedi (1983)                             3.362779
Raiders of the Lost Ark (1981)                        2.693297
Raiders of the Lost Ark (1981)                        2.680586
Austin Powers: International Man of Mystery (1997)    1.887164
Sting, The (1973)                                     1.837692
dtype: float64


Some of the same movies came up more than once, because they were similar to more than one movie I rated. We'll use groupby() to add together the scores from movies that show up more than once, so they'll count more:

In [7]:
simCandidates = simCandidates.groupby(simCandidates.index).sum()

In [8]:
simCandidates.sort_values(inplace = True, ascending = False)
simCandidates.head(10)

Empire Strikes Back, The (1980)              8.877450
Star Wars (1977)                             8.870971
Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
Sting, The (1973)                            3.329843
Cinderella (1950)                            3.245412
Field of Dreams (1989)                       3.222311
dtype: float64

filter out movies I've already rated, as recommending a movie I've already watched isn't helpful:

In [9]:
filteredSims = simCandidates.drop(myRatings.index)
filteredSims.head(10)

Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
Sting, The (1973)                            3.329843
Cinderella (1950)                            3.245412
Field of Dreams (1989)                       3.222311
Wizard of Oz, The (1939)                     3.200268
Dumbo (1941)                                 2.981645
dtype: float64

In [6]:

print(np.linspace(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [9]:
x = np.arange(4).reshape(2,2)

In [10]:
x


array([[0, 1],
       [2, 3]])

In [17]:
x = np.arange(4,8).reshape(2,2)

In [18]:
x

array([[4, 5],
       [6, 7]])

In [21]:
x = np.arange(20,120).reshape(10, 10)

In [22]:
x


array([[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [27]:
x = np.arange(20).reshape(4,5)
print(x)
print(x.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 2.  7. 12. 17.]


In [29]:

x = np.arange(12)

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
x = np.arange(30).reshape(3,5,2)

print(x[1][::2][1])

[14 15]


In [60]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [62]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [65]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x)
print(x.sum(1))

[[0 1]
 [1 1]
 [2 2]]
[1 2 4]


In [67]:
x = np.arange(4).reshape(2,2)
print(x)
y = np.vsplit(x,2)
print(y)
print(y[0])

[[0 1]
 [2 3]]
[array([[0, 1]]), array([[2, 3]])]
[[0 1]]


In [68]:
print(np.linspace(1, 10, 5))
print(np.arange(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [69]:
x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)

print(np.hstack((x,y)))

[[0 1 4 5]
 [2 3 6 7]]


In [70]:
print(np.repeat(3, 4))

[3 3 3 3]


In [73]:
x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [75]:
x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [76]:
x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]
