### define some distance metric between the items in your dataset,and find the K closest items (Instance/memory based learning) 

In [70]:
import pandas as pd

r_cols = ['user_id', 'movie_id', 'rating']
ratings = pd.read_csv('ml-100k/ml-100k/u.data', sep='\t', names=r_cols, usecols=range(3))
ratings.head()


user_id  movie_id  rating
0      196       242       3
1      186       302       3
2       22       377       1
3      244        51       2
4      166       346       1

###we'll group everything by movie ID, and compute the total number of ratings 
###(each movie's popularity) and the average rating for every movie


In [71]:
import numpy as np
movieProperties = ratings.groupby('movie_id').agg({'rating': [np.size, np.mean]})
movieProperties.head()


rating          
           size      mean
movie_id                 
1           452  3.878319
2           131  3.206107
3            90  3.033333
4           209  3.550239
5            86  3.302326

In [72]:
movieNumRatings = pd.DataFrame(movieProperties['rating']['size'])


In [73]:
movieNumRatings.head()

size
movie_id      
1          452
2          131
3           90
4          209
5           86

In [74]:
movieNormalizedNumRatings = movieNumRatings.apply(lambda x: (x - np.min(x)) / (np.max(x) - np.min(x)))


In [75]:
movieNormalizedNumRatings.head()

size
movie_id          
1         0.774914
2         0.223368
3         0.152921
4         0.357388
5         0.146048

In [76]:
##genre information from the u.item file. The way this works is there are 19 fields, each corresponding to a specific genre - a value of '0' means it is not in that genre, and '1' means it is in that genre. A movie may have more than one genre associated with it


In [77]:
gen_col = ['genre']
ratings = pd.read_csv('ml-100k/ml-100k/u.item', sep='\t', names=gen_col,encoding = "ISO-8859-1"
)

In [81]:
movieDict={}
with open(r'ml-100k/ml-100k/u.item', encoding = "ISO-8859-1") as f:
    temp = ''
    for line in f:
        #line.decode("ISO-8859-1")
        fields = line.rstrip('\n').split('|')
        
        movieID = int(fields[0])
        name = fields[1]
        genres = fields[5:25]
        ##print(genres)
        genres = map(int, genres)
        movieDict[movieID] = (name, np.array(list(genres)), movieNormalizedNumRatings.loc[movieID].get('size'), movieProperties.loc[movieID].rating.get('mean'))


In [82]:
movieDict[1]


('Toy Story (1995)',
 array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 0.7749140893470791,
 3.8783185840707963)

In [62]:
from scipy import spatial

In [93]:
def ComputeDistance(a, b):
    genresA = a[1]
    genresB = b[1]
    print(genresA)
    genreDistance = spatial.distance.cosine(genresA, genresB)
    popularityA = a[2]
    popularityB = b[2]
    popularityDistance = abs(popularityA - popularityB)
    return genreDistance + popularityDistance
    
ComputeDistance(movieDict[2], movieDict[4])


[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


0.8006872852233677

In [94]:
print(movieDict[2])

('GoldenEye (1995)', array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]), 0.22336769759450173, 3.2061068702290076)


In [95]:
print(movieDict[4])

('Get Shorty (1995)', array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 0.35738831615120276, 3.550239234449761)


In [96]:
import operator


In [97]:
avgRating


3.156701030927835

In [98]:
movieDict[1]


('Toy Story (1995)',
 array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 0.7749140893470791,
 3.8783185840707963)

In [99]:
##choose value of k 
